name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Render
        run: |
          curl -X POST https://api.render.com/deploy/success/YOUR_DEPLOY_HOOK_URL
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # Store your Render API key in GitHub Secrets
